version: '3'

services:
  mid-server:
    build:
      context: ./docker
      args: 
        URL: https://install.service-now.com/glide/distribution/builds/package/app-signed/mid/2021/09/16/mid.rome-06-23-2021__patch1-hotfix1-09-15-2021_09-16-2021_1434.linux.x86-64.zip
    env_file:
      - ./test/.env
    environment:
      - 'EXT_PARAMS=[{ "name": "mid.ssl.bootstrap.default.target_endpoint", "value": "sn.local", "type":"add" },{ "name": "mid.poll.time", "value": "5", "type":"add" }]'
    restart: 
      unless-stopped
    volumes:
      - ./test/custom_ca.crt:/opt/agent/custom_ca.crt
    healthcheck:
      test: pgrep -af wrapper-linux-x86-64 | grep `cat /opt/agent/work/mid.pid` || exit 1
      interval: 15s
      timeout: 5s
      retries: 6



